import Head from 'next/head'

import Navbar from "../components/Navbar";
import LeftSideBar from "../components/LeftSideBar";

import VideoGallery from "../components/VideoGallery";
import ShortoSlide from '../components/ShortoSlide';
import VideoGalleryTwo from '../components/VideoGalleryTwo';










export default function Home({data}) {


  
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://e7.pngegg.com/pngimages/630/300/png-clipart-trafalgar-d-water-law-donquixote-doflamingo-monkey-d-luffy-one-piece-piracy-one-piece-law-manga-jolly-roger.png" />
      </Head>
      <header>
         <Navbar/>
      </header>

      <main>


        <div className='flex bg-gradient-to-r from-gray-400 via-gray-500 to-gray-600'>
          <LeftSideBar/>
   
          <VideoGallery/>
        </div> 
        <div>
          <ShortoSlide/>
        </div>
          <VideoGalleryTwo/>
      </main>
      <footer>

      </footer>
    </div>
  );

}



